### ISSUE TITLE
Tilde diacritic is horizontally flipped

### ISSUE THREAD

**Issue by fitojb** [alexeiva/Comfortaa#1]
It should first ascend and then descend, the same way the stroke in an _N_ first ascends and then descends when you write it.

![captura de pantalla de 2016-10-29 13-41-34](https://cloud.githubusercontent.com/assets/554953/19831981/7708908c-9ddd-11e6-913a-4bf6fe4bc618.png)

**Comment by alexeiva** [comment]
@fitojb thank you for your eyes. Will be fixed.

**Comment by alexeiva** [comment]
Is fixed in aa51ff5
<img width="634" alt="screen shot 2016-10-31 at 15 32 02" src="https://cloud.githubusercontent.com/assets/16634089/19868683/7f212cf4-9f7f-11e6-9dc6-980bca4139d0.png">

**Comment by fitojb** [comment]
Thank you very much, @alexeiva! 😄
