### ISSUE TITLE
Vertical metrics

### ISSUE THREAD

**Issue by m4rc1e** [alexeiva/comfortaa#2]
@alexeiva @davelab6

Shall we revert these?

![screen shot 2016-12-13 at 13 29 14](https://cloud.githubusercontent.com/assets/7525512/21140419/3aba82ce-c138-11e6-9e8d-d053482ce79b.png)

**Comment by alexeiva** [comment]
no, please. This is a redesign from scratch project. No reason to keep old metrics.

**Comment by davelab6** [comment]
I'm OK with new networks

cc @omerziv

**Comment by m4rc1e** [comment]
Comfortaa's vertical metrics were released with Alexie's settings. It has been in production for a few months and we've had no complaints with the changed metrics.
