### ISSUE TITLE
Add 2 characters

### ISSUE THREAD

**Issue by davelab6** [alexeiva/comfortaa#7]
To support Kyrgyz please add U+04ca (ӊ) 

To support Uzbek please add U+02bb (ʻ)

**Comment by alexeiva** [comment]
> To support Kyrgyz please add U+04ca (ӊ)

ң `U+04A3` should be used for Kyrgyz support [Proof link 1](https://www.paratype.com/help/language/language1.asp?langCode=41) | [Proof link 2](https://www.eki.ee/letter/chardata.cgi?ucode=04A3)

**Comment by alexeiva** [comment]
> To support Uzbek please add U+02bb (ʻ)

Uzbek (Cyrillic) is fully supported by Comfortaa, and all GF Cyrillic Plus fonts.

For Uzbek (Latin) apostrophe (') `U+0027` should be used according to [Omniglot](https://www.omniglot.com/writing/uzbek.htm).

But it seems to be the practice to use LEFT SINGLE QUOTATION MARK (‘) `U+2018` instead. Seen on https://www.gov.uz/oz

In this case `U+02BB` is preferable over `U+0027`

**Comment by alexeiva** [comment]
Here is the fix https://github.com/alexeiva/comfortaa/releases/tag/3.101

**Comment by alexeiva** [comment]
On U+04CA (ӊ) I filed a ticket for CLDR here: https://unicode.org/cldr/trac/ticket/10739

**Comment by davelab6** [comment]
For Kyrgyz (ky) is U+04ca (ӊ) needed?

**Comment by alexeiva** [comment]
No, for Cyrillic Mongolian U+04ca (ӊ) is stray. New CLDR bug?

**Comment by davelab6** [comment]
Yep new bug please

**Comment by davelab6** [comment]
I want Google Fonts support to be superlative, so supporting Auxiliary parts :)
