### ISSUE TITLE
Glyph construction faults

### ISSUE THREAD

**Issue by m4rc1e** [alexeiva/comfortaa#8]
Many MM overlap issues and some missing glyphs to solve before we can release :-)

![comfortaa-collisions](https://user-images.githubusercontent.com/7525512/32144528-0578c83e-bcb2-11e7-8463-f2766280fade.gif)

![screen shot 2017-10-29 at 14 02 05](https://user-images.githubusercontent.com/7525512/32144513-d3c027ec-bcb1-11e7-8ac9-c959c34fcde3.png)

**Comment by alexeiva** [comment]
Very interesting. I am guessing 
https://github.com/alexeiva/comfortaa/commit/ce44a98f08f0d97ababc5dee38bc5ddca4af6e40 caused the issue.

Much easier to revert and add a component to fix #7

**Comment by m4rc1e** [comment]
Perhaps the curve directions were only set for one master?

**Comment by alexeiva** [comment]
Aha 00b10c8374d895309417509734ec1f9a47968f24 is clean

Something got messed up in 949ebbb992198333d90b8a1a0610925a8805761d
And later in ce44a98f08f0d97ababc5dee38bc5ddca4af6e40 I used @graphicore 's `correct path direction`, but didn't apply `set start point` of `sort paths` on top.

I couldn't fully repro this.
